# Generated by Django 4.2.4 on 2023-11-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.createjob')),
            ],
        ),
        migrations.CreateModel(
            name='Topic_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('create_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.create_topic')),
            ],
        ),
        migrations.DeleteModel(
            name='About_more_job_info',
        ),
    ]
