# Generated by Django 4.2.4 on 2023-11-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_create_topic_topic_field_delete_about_more_job_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_topic',
            old_name='name',
            new_name='title',
        ),
    ]
