# Generated by Django 4.2.4 on 2023-11-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_name_create_topic_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic_field',
            old_name='create_topic',
            new_name='choose_topic',
        ),
    ]
