# Generated by Django 4.2.4 on 2023-11-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_create_topic_topic_field_choose_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContiner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='topic_field',
            name='choose_topic',
        ),
        migrations.DeleteModel(
            name='Create_topic',
        ),
        migrations.DeleteModel(
            name='Topic_field',
        ),
    ]
