# Generated by Django 4.2.4 on 2023-11-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_formcontiner_remove_topic_field_choose_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formcontiner',
            old_name='descriptions',
            new_name='content',
        ),
    ]
