# Generated by Django 4.2.4 on 2023-11-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_descriptions_formcontiner_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormContiner',
            new_name='FormContainer',
        ),
    ]
