# Generated by Django 4.2.4 on 2023-11-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_formcontiner_formcontainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontainer',
            name='createjob',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.createjob'),
            preserve_default=False,
        ),
    ]
