# Generated by Django 4.2.4 on 2023-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_formcontainer_createjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
