# Generated by Django 4.2.4 on 2023-11-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_createjob_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='createjob',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
