# Generated by Django 4.2.4 on 2023-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_createjob_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createjob',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
