# Generated by Django 4.2.4 on 2023-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_createjob_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontainer',
            name='content',
            field=models.TextField(default='jobs requirements'),
        ),
        migrations.AlterField(
            model_name='formcontainer',
            name='title',
            field=models.CharField(default='jobs descriptions', max_length=255),
        ),
    ]
