# Generated by Django 4.2.4 on 2023-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_blog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_photo',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
